name: "Dagger CI"

on:
  push:
    branches: [ v0.2.x ]
    paths:
      - "**.sh"
      - "**.bash"
      - "**.go"
      - "**.cue"
      - "**.bats"
      - "Dockerfile"
      - "Makefile"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/dagger-ci.yml"
  pull_request:
    branches: [ v0.2.x ]
    paths:
      - "**.sh"
      - "**.bash"
      - "**.go"
      - "**.cue"
      - "**.bats"
      - "Dockerfile"
      - "Makefile"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/dagger-ci.yml"

env:
  DAGGER_LOG_FORMAT: plain
  DAGGER_CACHE_BASE: dagger-ci-build

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-22.04-16c-64g-600gb
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Setup Go"
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      # - name: "Set up dagger from source"
      #   run: |
      #     make dagger
      #     cp ./cmd/dagger/dagger /usr/local/bin

      - name: Sets env vars on push to v0.2.x
        run: |
          echo "DAGGER_CACHE_TO=type=gha,mode=max,scope=${{env.DAGGER_CACHE_BASE}}-v0.2.x" >> $GITHUB_ENV
          echo "DAGGER_CACHE_FROM=type=gha,scope=${{env.DAGGER_CACHE_BASE}}-v0.2.x" >> $GITHUB_ENV
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/v0.2.x' }}

      - name: Sets env vars on pull request
        run: |
          echo "DAGGER_CACHE_TO=type=gha,mode=max,scope=${{env.DAGGER_CACHE_BASE}}-${{github.event.number}}" >> $GITHUB_ENV
          echo "DAGGER_CACHE_FROM=type=gha,scope=${{env.DAGGER_CACHE_BASE}}-v0.2.x type=gha,scope=${{env.DAGGER_CACHE_BASE}}-${{github.event.number}}" >> $GITHUB_ENV
        if: ${{ github.event_name == 'pull_request' }}

      - name: Build
        uses: dagger/dagger-for-github@v3
        with:
          cmds: |
            do build
        env:
          DAGGER_LOG_LEVEL: "debug"

      - name: Print Buildkitd Logs
        if: ${{ failure() }}
        run: |
          docker logs dagger-buildkitd
