name: "Gitpod"

on:
  push:
    branches: [v0.2.x]
    paths:
      - ".gitpod.yml"
      - ".gitpod.Dockerfile"
      - "**.go"
      - "**.cue"
      - "Makefile"
      - "go.mod"
      - "go.sum"
  pull_request:
    branches: [v0.2.x]
    paths:
      - ".gitpod.yml"
      - ".gitpod.Dockerfile"
      - "**.go"
      - "**.cue"
      - "Makefile"
      - "go.mod"
      - "go.sum"

env:
  DAGGER_LOG_FORMAT: plain

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Expose GitHub Runtime"
        uses: crazy-max/ghaction-github-runtime@v1

      - name: "Set up dagger"
        uses: dagger/dagger-for-github@v2
        with:
          install-only: true

      - name: Build
        env:
          DAGGER_LOG_LEVEL: "debug"
          DAGGER_LOG_FORMAT: "plain"
        run: |
          dagger do gitpod
